mybatis:
  config-location: classpath:config/sqlMapConfig.xml
  type-aliases-package: com.funong.newerp.dal.entity
  mapper-locations:    classpath:config/mapper/*Mapper.xml
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/funong_msc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    #url: jdbc:mysql://192.168.0.248:3306/erpv3.1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: 15f2f06bf2
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200