server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.0.248:3306/erpv3.1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 15f2f06bf2
